<?php

namespace Pingumask\Plectrum\Partial;



abstract class DiscordConst
{
    const FLAG_SUPPRESS_EMBEDS = 1 << 2;
    const FLAG_EPHEMERAL = 1 << 6;

    const OPTION_TYPE_SUB_COMMAND = 1;
    const OPTION_TYPE_SUB_COMMAND_GROUP = 2;
    const OPTION_TYPE_STRING = 3;
    const OPTION_TYPE_INTEGER = 4;
    const OPTION_TYPE_BOOLEAN = 5;
    const OPTION_TYPE_USER = 6;
    const OPTION_TYPE_CHANNEL = 7;
    const OPTION_TYPE_ROLE = 8;
    const OPTION_TYPE_MENTIONABLE = 9;
    const OPTION_TYPE_NUMBER = 10;
    const OPTION_TYPE_ATTACHMENT = 11;

    const INTERACTION_TYPE_PING = 1;
    const INTERACTION_TYPE_APPLICATION_COMMAND = 2;
    const INTERACTION_TYPE_MESSAGE_COMPONENT = 3;
    const INTERACTION_TYPE_APPLICATION_COMMAND_AUTOCOMPLETE = 4;
    const INTERACTION_TYPE_MODAL_SUBMIT = 5;

    const INTERACTION_CALLBACK_PONG = 1;
    const INTERACTION_CALLBACK_CHANNEL_MESSAGE_WITH_SOURCE = 4;
    const INTERACTION_CALLBACK_DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE = 5;
    const INTERACTION_CALLBACK_DEFERRED_UPDATE_MESSAGE = 6;
    const INTERACTION_CALLBACK_UPDATE_MESSAGE = 7;
    const INTERACTION_CALLBACK_APPLICATION_COMMAND_AUTOCOMPLETE_RESULT = 8;
    const INTERACTION_CALLBACK_MODAL = 9;
    const INTERACTION_CALLBACK_PREMIUM_REQUIRED = 10;
}
